[workspace]
authors = ["omar-abdelgawad <omar.abdelgawad@ejust.edu.eg>"]
channels = ["conda-forge","https://prefix.dev/aurobotics",  "robostack-jazzy"]
name = "rov_ws"
platforms = ["linux-64"]
version = "0.1.0"
preview = ["pixi-build"]

[tasks]

[dependencies]
# opencv = { version = "*", channel = "https://prefix.dev/aurobotics"}
information-sheet-problem = { git = "https://github.com/ejustroboticsclub/mate-rov-2026-information-sheet-problem", tag = "v3" }
crab-detection = { git = "https://github.com/ejustroboticsclub/mate-rov-2026-crab-detection", tag = "v4" }
# crab-detection = { path = "../crab-detection/" }
## resolving errors
setuptools = "<82"
ros-jazzy-desktop = "*"

[pypi-dependencies]
torch = ">=2.11.0, <3"
torchvision = ">=0.26.0, <0.27"
pyqt5 = "*"
paramiko = "*"
screeninfo = "*"
